### PR TITLE
Implemented support for filtering based on custom fields using a where argument

### PR DESCRIPTION
**Pull request by wcha-peter**
Allows for filtering of results of the api4 short code with custom fields containing dots, as discusses in PROJ-2246

### CODE REVIEW

**Review by agileware-fj — CHANGES_REQUESTED** [review]
Thanks a heap for having a crack at this, Peter.

I'd like to request though, that when adding complex filters like this, we try to avoid deviating from the CiviCRM APIv4 syntax, which is why I suggested using JSON with the `[ field, op, value ]` syntax in the first place.

The great advantages with that are that we can then just pass it into `json_decode` and defer validation to the API call, and most people can recognise JSON fairly quick rather than having to interpret an unusual syntax.

Would you be able to change it to work like that and resubmit?

**Comment by wcha-peter** [comment]
Thanks for that Francis. 

In terms of providing json input to WordPress shortcodes, square braces are not valid anywhere within wordpress arguments, so they would need to be encoded using something else - possibly '(' to avoid conflicts with other json syntax.

However, that's starting to stray into defining our own custom syntax - would you still be fine with almost json syntax like (field, op, value) ?

**Comment by wcha-peter** [comment]
Just implemented a json based solution as per my above comments, using brackets in place of square brackets. Please let me know your thoughts on this approach, and if you're happy I can flatten the commits,

**Review by agileware-fj — COMMENTED** [review]
Thanks @wcha-peter 

Because of _course_ shortcode parsing can't cope with square brackets anywhere.

The overall idea is okay and I'm happy to go with replacing [] with () for the syntax, but the implementation is going to need to take into consideration when values have parentheses in them before I can merge - e.g. `("custom.field", "=" , "Turtles (are cool)")`

**Comment by wcha-peter** [comment]
Superseded by https://github.com/agileware/wp-civicrm-ux/pull/26

**Pull request closed without merging**
